language: python
python:
- 3.5
install:
- pip install -r requirements.txt
before_script:
- sudo apt-get install -y nodejs
- ln -s $HOME/.local/bin/node /usr/bin/nodejs
- sudo apt-get install -y npm
- npm install phantomjs
- export PATH=$PATH:$HOME/node_modules/.bin
script: nosetests
after_success:
- "./auto.sh"
